### ISSUE TITLE
Swiggy works

### ISSUE THREAD

**Issue by cvzi** [cvzi/swiggy-non-veg-userscript#1]
Seems to work for swiggy. I have not added zomato yet, but the website is almost the same, so it should be only minor changes @Nzzyme 

I have found three types of restaurants: 
 * some have only veg dishes, so we can ignore these
 * some have only "non veg" dishes, we can ignore these as well
 * some have a "veg only" button, in this case the "non veg" button is added

There may be other types/different buttons, but I have not found any yet.

**Comment by Nzzyme** [comment]
Thank you so much. Appreciate it! I was checking the script and it works fine for restaurants where there are both veg & non-veg dishes.

However, when I loaded a restaurant which is a pure veg restaurant, the "Pure Veg" label seems to keep loading indefinitely and I see a horizontal scroll-bar with this label. Can you please check?

Ex: https://www.swiggy.com/restaurants/hotel-sri-raghavendra-pure-veg-defence-colony-jj-nagar-a-s-rao-nagar-and-sainikpuri-hyderabad-79267

Screenshots:
https://prnt.sc/11utdax

https://prnt.sc/11utejo

**Comment by cvzi** [comment]
Fixed pure veg and added zomato

**Comment by Nzzyme** [comment]
Thanks. I checked and everything works fine now.

**Comment by Nzzyme** [comment]
Hi @cvzi I was checking on Zomato and I was not able to click on the check-box (Non-veg) and check it. Can you please check?

Example Link: https://www.zomato.com/ncr/the-biryani-experiment-shakarpur-new-delhi/order

**Comment by cvzi** [comment]
Should work again

**Comment by Nzzyme** [comment]
Ok, I was trying to click on the check box itself (square) and it did not check it. It does for the other Veg option. But when I click on the text "Non veg", it gets checked.

**Comment by cvzi** [comment]
Checkbox should work as well now

**Comment by Nzzyme** [comment]
Yes, it's working fine now. Thanks!
