### ISSUE TITLE
Script Not Working

### ISSUE THREAD

**Issue by Nzzyme** [cvzi/swiggy-non-veg-userscript#2]
Hi, hope you are doing fine.

I just installed the script in Edge and observed that it no longer works on Swiggy & Zomato. When I check the box for Non-Veg, I see veg dishes too. I observed that they have changed the icon of the non-veg dishes to:

![image](https://user-images.githubusercontent.com/6959116/147447768-c06b09e1-7d09-4a1d-ab34-aeb5228a0e85.png)
 
Link that I tried as an example:

https://www.swiggy.com/restaurants/new-shama-chicken-corner-karol-bagh-delhi-450485

Zomato no longer supports online ordering through their web page (one has to install their app for ordering). However, it would be good if your script continues to filter and show us the non-veg dishes for quick reference. However, sadly, the same behavior is seen even with Zomato. That is after checking the box for non-veg, I am still seeing veg dishes. 

Can you please check and fix?

Thanks & have a great day!

**Comment by cvzi** [comment]
I have updated it

Install link:
https://greasyfork.org/scripts/425352-swiggy-zomato-non-veg-dishes-only/code/Swiggy%20%20Zomato:%20Non%20Veg%20dishes%20only.user.js

**Comment by Nzzyme** [comment]
> I have updated it
> 
> Install link: https://greasyfork.org/scripts/425352-swiggy-zomato-non-veg-dishes-only/code/Swiggy%20%20Zomato:%20Non%20Veg%20dishes%20only.user.js

Works fine now.. Thanks a lot!
